name: News Updater
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Fetching News and saving locally
        uses: gautemo/fetch-api-data-action@1.1.0
        with:
          url: 'https://newsapi.org/v2/top-headlines?category=technology&language=en&apiKey=${{secrets.API_KEY}}'
          file: 'public/news.json'
      - name: setup git config
        run: |
          git config user.name "GitHub Actions News Updater Bot"
          git config user.email "<>"
      - name: commit
        run: |
          git add .
          git commit -m "$(date +%d/%b/%y) news updated"
          git push origin main
